A=set([1,2,3,4])
B=set([2,4,6,7])

print('Set A')
print(A)

print('Set B')
print(B)
print(1 in A)
print('Union')
print(A|B)
print('Union using function')
print(A.union(B))
print('Intersection')
print(A&B)
print('Intersection using function')
print(A.intersection(B))
print('Difference')
print(A-B)
print('Difference using function')
print(A.difference(B))
print('Symmetric Difference')
print(A^B)
print('Symmetric Difference using function')
print(A.symmetric_difference(B))
